Add aggregate fuzzer nightly job. (#3225)
Summary:
Add aggregation fuzzer nightly job. Tested the command locally and ran it for 10 odd minutes. This job will run for 1 hour every night.

Pull Request resolved: https://github.com/facebookincubator/velox/pull/3225

Reviewed By: mbasmanova

Differential Revision: D41275303

Pulled By: kgpai

fbshipit-source-id: 6e4d8af2331ae49047d130596bab8d166ceafae0

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -39,6 +39,7 @@ workflows:
     jobs:
       - doc-gen-job
       - linux-fuzzer-run
+      - linux-aggregate-fuzzer-run
 
   # Hourly build on weekdays
   weekday:
@@ -428,6 +429,41 @@ jobs:
           no_output_timeout: 20m
       - store_artifacts:
           path: '/tmp/fuzzer.log'
+      - post-steps
+
+  linux-aggregate-fuzzer-run:
+    executor: build
+    steps:
+      - pre-steps
+      - run:
+          name: Build
+          command: |
+            make debug NUM_THREADS=16 MAX_HIGH_MEM_JOBS=8 MAX_LINK_JOBS=8
+            ccache -s
+          no_output_timeout: 2h
+      - run:
+          # Run Aggregate Fuzzer, save the output to /tmp/aggregate_fuzzer.log, and upload the file
+          # as job artifact to make it convenient for users to inspect it -
+          # these logs can also be quite large. Always prints the last 1k lines to
+          # the job output for context.
+          name: "Run Aggregate Fuzzer Tests"
+          command: |
+            echo -e "The logs will be saved to \"/tmp/aggregate_fuzzer.log\" and uploaded" \
+                    "as a job artifact (check the \"Artifacts\" tab above)."
+            _build/debug/velox/expression/tests/velox_aggregation_fuzzer_test \
+                --seed ${RANDOM} \
+                --duration_sec 3600 \
+                --logtostderr=1 \
+                --minloglevel=0 \
+              2>&1 | tee /tmp/aggregate_fuzzer.log || ( \
+                tail -n 1000 /tmp/aggregate_fuzzer.log;
+                echo "FAIL: Aggregate Fuzzer run failed";
+                exit 1; \
+              )
+            echo -e "\n\nAggregate Fuzzer run finished successfully."
+          no_output_timeout: 120m
+      - store_artifacts:
+          path: '/tmp/aggregate_fuzzer.log'
       - post-steps
 
   format-check:
