Add spark fuzzer to nightly job. (#3374)
Summary:
This job runs for 10 minutes, and stores the resultant logs as artifacts. The artifacts can be accessed via the artifacts section in circleci for the particular instance of the run. We also rename linux-fuzzer-run to linux-presto-fuzzer-run.

Pull Request resolved: https://github.com/facebookincubator/velox/pull/3374

Reviewed By: mbasmanova

Differential Revision: D41695975

Pulled By: kgpai

fbshipit-source-id: 7f53d64ac9c2db46c1ee90ce12adddfd570ee9c0

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -38,7 +38,8 @@ workflows:
                - main
     jobs:
       - doc-gen-job
-      - linux-fuzzer-run
+      - linux-presto-fuzzer-run
+      - linux-spark-fuzzer-run
       - linux-aggregate-fuzzer-run
       - docker-compose-ubuntu-cpp
       - docker-compose-centos-cpp
@@ -405,7 +406,7 @@ jobs:
           no_output_timeout: 1h
       - post-steps
 
-  linux-fuzzer-run:
+  linux-presto-fuzzer-run:
     executor: build
     environment:
       VELOX_DEPENDENCY_SOURCE: SYSTEM
@@ -443,6 +444,43 @@ jobs:
           no_output_timeout: 20m
       - store_artifacts:
           path: '/tmp/fuzzer.log'
+      - post-steps
+
+  linux-spark-fuzzer-run:
+    executor: build
+    environment:
+      VELOX_DEPENDENCY_SOURCE: SYSTEM
+    steps:
+      - pre-steps
+      - run:
+          name: Build
+          command: |
+            make debug NUM_THREADS=16 MAX_HIGH_MEM_JOBS=8 MAX_LINK_JOBS=8
+            ccache -s
+          no_output_timeout: 1h
+      - run:
+          # Run Spark Fuzzer, save the output to /tmp/spark_fuzzer.log, and upload the file
+          # as job artifact to make it convenient for users to inspect it -
+          # these logs can also be quite large. Always prints the last 1k lines to
+          # the job output for context.
+          name: "Run Spark Fuzzer Tests"
+          command: |
+            echo -e "The logs will be saved to \"/tmp/spark_fuzzer.log\" and uploaded" \
+                    "as a job artifact (check the \"Artifacts\" tab above)."
+            _build/debug/velox/expression/tests/spark_expression_fuzzer_test \
+                --seed ${RANDOM} \
+                --duration_sec 600 \
+                --logtostderr=1 \
+                --minloglevel=0 \
+              2>&1 | tee /tmp/spark_fuzzer.log || ( \
+                tail -n 1000 /tmp/spark_fuzzer.log;
+                echo "FAIL: Fuzzer run failed";
+                exit 1; \
+              )
+            echo -e "\n\nSpark Fuzzer run finished successfully."
+          no_output_timeout: 20m
+      - store_artifacts:
+          path: '/tmp/spark_fuzzer.log'
       - post-steps
 
   linux-aggregate-fuzzer-run:
