Add publishing docs to presto release publish action

diff --git a/.github/workflows/presto-release-publish.yml b/.github/workflows/presto-release-publish.yml
--- a/.github/workflows/presto-release-publish.yml
+++ b/.github/workflows/presto-release-publish.yml
@@ -4,33 +4,33 @@ on:
   workflow_dispatch:
     inputs:
       RELEASE_VERSION:
-        description: 'Release version (e.g., 0.290)'
+        description: 'Release version (e.g., 0.292)'
         required: true
-      create_release_tag:
-        description: 'Create release tag'
+      publish_release_tag:
+        description: 'Publish release tag'
         type: boolean
         default: true
         required: false
       release-notes-commit:
-        description: 'Commit SHA of release notes(required when create_release_tag is checked)'
+        description: 'Commit SHA of release notes(required when publish_release_tag is checked)'
         required: false
       publish_maven:
-        description: 'Publish Maven artifacts'
+        description: 'Publish maven artifacts'
         type: boolean
         default: true
         required: false
       publish_docker:
-        description: 'Publish Docker images'
+        description: 'Publish docker images'
         type: boolean
         default: true
         required: false
       publish_native_docker:
-        description: 'Publish Native Docker images'
+        description: 'Publish native docker images'
         type: boolean
         default: true
         required: false
       tag_image_as_latest:
-        description: 'Tag the image as latest version'
+        description: 'Tag the image as latest'
         type: boolean
         default: true
         required: false
@@ -38,26 +38,30 @@ on:
         description: 'Dependency image(e.g., prestodb/presto-native-dependency:0.290-20241014120930-e1fc090)'
         required: false
         default: ''
+      publish_docs:
+        description: 'Publish docs'
+        type: boolean
+        default: true
+        required: false
 
 env:
-  VERSION: ${{ github.event.inputs.RELEASE_VERSION }}
   DOCKER_REPO: ${{ github.repository }}
   ORG_NAME: ${{ github.repository_owner }}
   IMAGE_NAME: presto-native
-  RELEASE_BRANCH: release-${{ github.event.inputs.RELEASE_VERSION }}
-  RELEASE_TAG: ${{ github.event.inputs.RELEASE_VERSION }}
-  RELEASE_NOTES_COMMIT: ${{ github.event.inputs.release-notes-commit }}
+  RELEASE_BRANCH: release-${{ inputs.RELEASE_VERSION }}
+  RELEASE_TAG: ${{ inputs.RELEASE_VERSION }}
+  RELEASE_NOTES_COMMIT: ${{ inputs.release-notes-commit }}
 
 jobs:
   tag-release:
-    if: ${{ github.event.inputs.create_release_tag == 'true' }}
+    if: ${{ github.event.inputs.publish_release_tag == 'true' }}
     runs-on: ubuntu-latest
     environment: release
     steps:
       - name: Validate release notes commit
         if: ${{ github.event.inputs.release-notes-commit == '' }}
         run: |
-          echo "Error: release-notes-commit is required when create_release_tag is true"
+          echo "Error: release-notes-commit is required when publish_release_tag is true"
           exit 1
 
       - name: Checkout repository
@@ -92,8 +96,8 @@ jobs:
   publish-maven-artifacts:
     needs: tag-release
     if: |
-      (github.event.inputs.publish_maven == 'true' || github.event.inputs.publish_docker == 'true') &&
-      (github.event.inputs.create_release_tag != 'true' || success())
+      (github.event.inputs.publish_maven == 'true' || github.event.inputs.publish_docker == 'true' || github.event.inputs.publish_docs == 'true') &&
+      (github.event.inputs.publish_release_tag != 'true' || success())
     runs-on: ubuntu-latest
     environment: release
     timeout-minutes: 60
@@ -120,7 +124,7 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
         with:
-          ref: ${{ env.VERSION }}
+          ref: ${{ env.RELEASE_TAG }}
           token: ${{ secrets.PRESTODB_CI_TOKEN }}
           fetch-depth: 0
           fetch-tags: true
@@ -169,11 +173,12 @@ jobs:
       - name: Upload artifacts
         uses: actions/upload-artifact@v4
         with:
-          name: presto-artifacts-${{ env.VERSION }}
+          name: presto-artifacts-${{ env.RELEASE_TAG }}
           retention-days: 1
           path: |
             presto-server/target/presto-server-*.tar.gz
             presto-cli/target/presto-cli-*-executable.jar
+            presto-docs/target/presto-docs-*.zip
 
       - name: Set up GPG key
         run: |
@@ -217,12 +222,12 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
         with:
-          ref: ${{ env.VERSION }}
+          ref: ${{ env.RELEASE_TAG}}
 
       - name: Download artifacts
         uses: actions/download-artifact@v4
         with:
-          name: presto-artifacts-${{ env.VERSION }}
+          name: presto-artifacts-${{ env.RELEASE_TAG }}
           path: ./
 
       - name: Login to dockerhub
@@ -230,13 +235,6 @@ jobs:
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
-
-      - name: Login to gitHub container registry
-        uses: docker/login-action@v3.3.0
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.PRESTODB_CI_TOKEN }}
 
       - name: Set up qemu
         uses: docker/setup-qemu-action@v3
@@ -262,19 +260,17 @@ jobs:
           file: docker/Dockerfile
           push: true
           build-args: |
-            PRESTO_VERSION=${{ env.VERSION }}
+            PRESTO_VERSION=${{ env.RELEASE_TAG }}
             JMX_PROMETHEUS_JAVAAGENT_VERSION=0.20.0
           tags: |
-            ${{ env.DOCKER_REPO }}:${{ env.VERSION }}
+            ${{ env.DOCKER_REPO }}:${{ env.RELEASE_TAG }}
             ${{ github.event.inputs.tag_image_as_latest == 'true' && format('{0}:latest', env.DOCKER_REPO) || '' }}
-            ghcr.io/${{ github.repository }}:${{ env.VERSION }}
-            ${{ github.event.inputs.tag_image_as_latest == 'true' && format('ghcr.io/{0}:latest', github.repository) || '' }}
 
   publish-native-images:
     needs: tag-release
     if: |
       github.event.inputs.publish_native_docker == 'true' &&
-      (github.event.inputs.create_release_tag != 'true' || success())
+      (github.event.inputs.publish_release_tag != 'true' || success())
     runs-on: ubuntu-latest
     permissions:
       contents: read
@@ -287,7 +283,7 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
         with:
-          ref: ${{ env.VERSION }}
+          ref: ${{ env.RELEASE_TAG }}
           submodules: true
 
       - name: Initialize Prestissimo submodules
@@ -313,7 +309,7 @@ jobs:
           if [[ -n "${{ github.event.inputs.dependency_image }}" ]]; then
             echo "DEPENDENCY_IMAGE=${{ github.event.inputs.dependency_image }}" >> $GITHUB_ENV
           else
-            echo "DEPENDENCY_IMAGE=ghcr.io/${{ github.repository_owner }}/presto-native-dependency:${{ env.VERSION }}-${{ env.COMMIT_SHA }}" >> $GITHUB_ENV
+            echo "DEPENDENCY_IMAGE=ghcr.io/${{ github.repository_owner }}/presto-native-dependency:${{ env.RELEASE_TAG }}-${{ env.COMMIT_SHA }}" >> $GITHUB_ENV
           fi
 
       - name: Build Dependency Image
@@ -325,43 +321,129 @@ jobs:
           else
             echo "Building new depedency image"
             docker compose build centos-native-dependency
-            docker tag presto/prestissimo-dependency:centos9 ghcr.io/${{ github.repository_owner }}/presto-native-dependency:${{ env.VERSION }}-${{ env.COMMIT_SHA }}
-            docker push ghcr.io/${{ github.repository_owner }}/presto-native-dependency:${{ env.VERSION }}-${{ env.COMMIT_SHA }}
+            docker tag presto/prestissimo-dependency:centos9 ghcr.io/${{ github.repository_owner }}/presto-native-dependency:${{ env.RELEASE_TAG }}-${{ env.COMMIT_SHA }}
+            docker push ghcr.io/${{ github.repository_owner }}/presto-native-dependency:${{ env.RELEASE_TAG }}-${{ env.COMMIT_SHA }}
           fi
           docker images
 
       - name: Build Runtime Image
         working-directory: presto-native-execution
         run: |
-          if docker pull ghcr.io/${{ github.repository_owner }}/presto-native:${{ env.VERSION }}-${{ env.COMMIT_SHA }}; then
-            docker tag ghcr.io/${{ github.repository_owner }}/presto-native:${{ env.VERSION }}-${{ env.COMMIT_SHA }} docker.io/presto/prestissimo-runtime:centos9
-          else
-            docker compose build centos-native-runtime
-            docker tag presto/prestissimo-runtime:centos9 ghcr.io/${{ github.repository_owner }}/presto-native:${{ env.VERSION }}-${{ env.COMMIT_SHA }}
-            docker push ghcr.io/${{ github.repository_owner }}/presto-native:${{ env.VERSION }}-${{ env.COMMIT_SHA }}
-          fi
+          docker compose build centos-native-runtime
 
       - name: Add release tag
         working-directory: presto-native-execution
         run: |
-          docker tag presto/prestissimo-runtime:centos9 ${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
+          docker tag presto/prestissimo-runtime:centos9 ${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_TAG }}
           if [[ "${{ github.event.inputs.tag_image_as_latest }}" == "true" ]]; then
             docker tag presto/prestissimo-runtime:centos9 ${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}:latest
           fi
 
       - name: Push to DockerHub
         run: |
-          docker push ${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
+          docker push ${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_TAG }}
           if [[ "${{ github.event.inputs.tag_image_as_latest }}" == "true" ]]; then
-            docker tag ${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }} ${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}:latest
+            docker tag ${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_TAG }} ${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}:latest
             docker push ${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}:latest
           fi
 
-      - name: Tag and push to GitHub Packages
+  publish-docs:
+    needs: publish-maven-artifacts
+    if: ${{ github.event.inputs.publish_docs == 'true' && always() }}
+    runs-on: ubuntu-latest
+    environment: release
+
+    steps:
+      - name: Checkout presto
+        uses: actions/checkout@v4
+        with:
+          repository: ${{ github.repository_owner }}/presto
+          path: presto
+          ref: master
+          fetch-depth: 0
+          fetch-tags: true
+          show-progress: false
+
+      - name: Checkout prestodb.github.io
+        uses: actions/checkout@v4
+        with:
+          repository: ${{ github.repository_owner }}/prestodb.github.io
+          path: prestodb.github.io
+          ref: source
+          token: ${{ secrets.PRESTODB_CI_TOKEN }}
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: '18.x'
+
+      - name: Configure Git
         run: |
-          docker tag ${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }} ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
-          docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
-          if [[ "${{ github.event.inputs.tag_image_as_latest }}" == "true" ]]; then
-            docker tag ${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }} ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
-            docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
+          cd ${{ github.workspace }}/prestodb.github.io
+          git config --global --add safe.directory ${{ github.workspace }}/prestodb.github.io
+          git config --global user.email "ci@lists.prestodb.io"
+          git config --global user.name "prestodb-ci"
+          git log --pretty="format:%ce: %s" -5
+
+      - name: Download artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: presto-artifacts-${{ env.RELEASE_TAG }}
+          path: ${{ github.workspace }}/build
+
+      - name: Update Docs
+        run: |
+          cd ${{ github.workspace }}/prestodb.github.io
+          ls -al
+
+          cd website && yarn install && cd ..
+          LAST_RELEASE_VERSION="0.$((${RELEASE_TAG#0.} - 1))"
+          echo "Last release version: ${LAST_RELEASE_VERSION}"
+
+          TARGET=website/static/docs/${RELEASE_TAG}
+          CURRENT=website/static/docs/current
+
+          if [[ -e ${TARGET} ]]; then
+            echo "Error: ${TARGET} already exists"
+            exit 1
           fi
+
+          mv ${{ github.workspace }}/build/presto-docs/target/presto-docs-${RELEASE_TAG}.zip .
+          unzip presto-docs-${RELEASE_TAG}.zip | head -n 5
+          mv html ${TARGET}
+          unlink ${CURRENT}
+          ln -sf ${RELEASE_TAG} ${CURRENT}
+          git add ${TARGET} ${CURRENT}
+          git status | head -n 5
+
+          DATE=$(TZ=America/Los_Angeles date '+%B %d, %Y')
+          echo "Update the version number and stats in javascript for rendering across the site"
+          VERSION_JS=website/static/static/js/version.js
+
+          echo "const presto_latest_presto_version = '${RELEASE_TAG}';" > ${VERSION_JS}
+          GIT_LOG="git -C ../presto log --use-mailmap ${LAST_RELEASE_VERSION}..${RELEASE_TAG}"
+          NUM_COMMITS=$(${GIT_LOG} --format='%aE' | wc -l | awk '{$1=$1;print}')
+          NUM_CONTRIBUTORS=$(${GIT_LOG} --format='%aE' | sort | uniq | wc -l | awk '{$1=$1;print}')
+          NUM_COMMITTERS=$(${GIT_LOG} --format='%cE' | sort | uniq | wc -l | awk '{$1=$1;print}')
+          echo "const presto_latest_num_commits = ${NUM_COMMITS};" >> ${VERSION_JS}
+          echo "const presto_latest_num_contributors = ${NUM_CONTRIBUTORS};" >> ${VERSION_JS}
+          echo "const presto_latest_num_committers = ${NUM_COMMITTERS};" >> ${VERSION_JS}
+          echo "const presto_latest_date = '${DATE}';" >> ${VERSION_JS}
+          cat ${VERSION_JS}
+          git add ${VERSION_JS}
+          git status | head -n 5
+
+      - name: Push Updates
+        run: |
+          cd ${{ github.workspace }}/prestodb.github.io
+          git status | head -n 5
+          git commit -m "Add ${RELEASE_TAG} docs" | head -n 5
+          git checkout -b "${RELEASE_TAG}-docs"
+          git push origin "${RELEASE_TAG}-docs"
+
+      - name: Create pull request
+        env:
+          GH_TOKEN: ${{ secrets.PRESTODB_CI_TOKEN }}
+        run: |
+          cd ${{ github.workspace }}/prestodb.github.io
+          gh pr create --title "Add ${RELEASE_TAG} docs" --body "Add ${RELEASE_TAG} docs" --base source --head "${RELEASE_TAG}-docs"
